-- Sprint 26.0.3 — NEEJEE Taxonomy Schema + Seed (FK-drop strategy, bulletproof)
-- Drops FK constraint, inserts all rows with correct parentId, re-adds FK at end.
-- Cannot fail under any Postgres SQL editor.

-- =========================================================
-- 1) SCHEMA ADDITIONS
-- =========================================================
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "level" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "path" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "hidden" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "aiGenerated" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "gender" TEXT;
CREATE INDEX IF NOT EXISTS "Category_level_parentId_idx" ON "Category"("level", "parentId");
CREATE INDEX IF NOT EXISTS "Category_path_idx" ON "Category"("path");
CREATE INDEX IF NOT EXISTS "Category_hidden_idx" ON "Category"("hidden");

CREATE TABLE IF NOT EXISTS "CategoryRedirect" (
  "id" TEXT PRIMARY KEY,
  "fromSlug" TEXT NOT NULL UNIQUE,
  "toSlug" TEXT NOT NULL,
  "permanent" BOOLEAN NOT NULL DEFAULT TRUE,
  "hitCount" INTEGER NOT NULL DEFAULT 0,
  "lastHitAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS "CategoryRedirect_fromSlug_idx" ON "CategoryRedirect"("fromSlug");

-- =========================================================
-- 2) DROP FK CONSTRAINT (will re-add at the end)
-- =========================================================
ALTER TABLE "Category" DROP CONSTRAINT IF EXISTS "Category_parentId_fkey";

-- =========================================================
-- 3) INSERT all 307 rows with real parentId values (FK is off)
-- =========================================================
INSERT INTO "Category" ("id","slug","name","parentId","order","active","hidden","featured","aiGenerated","level","path","gender","createdAt","updatedAt") VALUES
  ('cat_women','women','Women',NULL,1,TRUE,FALSE,FALSE,FALSE,1,'women',NULL,NOW(),NOW()),
  ('cat_women-sarees','women-sarees','Sarees','cat_women',1,TRUE,FALSE,FALSE,FALSE,2,'women/sarees',NULL,NOW(),NOW()),
  ('cat_women-sarees-banarasi','women-sarees-banarasi','Banarasi','cat_women-sarees',1,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/banarasi',NULL,NOW(),NOW()),
  ('cat_women-sarees-kanchipuram','women-sarees-kanchipuram','Kanchipuram','cat_women-sarees',2,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/kanchipuram',NULL,NOW(),NOW()),
  ('cat_women-sarees-chanderi','women-sarees-chanderi','Chanderi','cat_women-sarees',3,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/chanderi',NULL,NOW(),NOW()),
  ('cat_women-sarees-maheshwari','women-sarees-maheshwari','Maheshwari','cat_women-sarees',4,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/maheshwari',NULL,NOW(),NOW()),
  ('cat_women-sarees-patola','women-sarees-patola','Patola','cat_women-sarees',5,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/patola',NULL,NOW(),NOW()),
  ('cat_women-sarees-baluchari','women-sarees-baluchari','Baluchari','cat_women-sarees',6,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/baluchari',NULL,NOW(),NOW()),
  ('cat_women-sarees-jamdani','women-sarees-jamdani','Jamdani','cat_women-sarees',7,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/jamdani',NULL,NOW(),NOW()),
  ('cat_women-sarees-pochampalli','women-sarees-pochampalli','Pochampalli','cat_women-sarees',8,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/pochampalli',NULL,NOW(),NOW()),
  ('cat_women-sarees-mysore-silk','women-sarees-mysore-silk','Mysore Silk','cat_women-sarees',9,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/mysore-silk',NULL,NOW(),NOW()),
  ('cat_women-sarees-tussar','women-sarees-tussar','Tussar','cat_women-sarees',10,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/tussar',NULL,NOW(),NOW()),
  ('cat_women-sarees-bandhani','women-sarees-bandhani','Bandhani','cat_women-sarees',11,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/bandhani',NULL,NOW(),NOW()),
  ('cat_women-sarees-leheriya','women-sarees-leheriya','Leheriya','cat_women-sarees',12,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/leheriya',NULL,NOW(),NOW()),
  ('cat_women-sarees-linen','women-sarees-linen','Linen','cat_women-sarees',13,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/linen',NULL,NOW(),NOW()),
  ('cat_women-sarees-cotton','women-sarees-cotton','Cotton','cat_women-sarees',14,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/cotton',NULL,NOW(),NOW()),
  ('cat_women-sarees-everyday','women-sarees-everyday','Everyday','cat_women-sarees',15,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/everyday',NULL,NOW(),NOW()),
  ('cat_women-sarees-bridal','women-sarees-bridal','Bridal','cat_women-sarees',16,TRUE,FALSE,FALSE,FALSE,3,'women/sarees/bridal',NULL,NOW(),NOW()),
  ('cat_women-apparel','women-apparel','Apparel','cat_women',2,TRUE,FALSE,FALSE,FALSE,2,'women/apparel',NULL,NOW(),NOW()),
  ('cat_women-apparel-kurtas','women-apparel-kurtas','Kurtas','cat_women-apparel',1,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/kurtas',NULL,NOW(),NOW()),
  ('cat_women-apparel-kurta-sets','women-apparel-kurta-sets','Kurta Sets','cat_women-apparel',2,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/kurta-sets',NULL,NOW(),NOW()),
  ('cat_women-apparel-anarkali','women-apparel-anarkali','Anarkali','cat_women-apparel',3,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/anarkali',NULL,NOW(),NOW()),
  ('cat_women-apparel-lehengas','women-apparel-lehengas','Lehengas','cat_women-apparel',4,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/lehengas',NULL,NOW(),NOW()),
  ('cat_women-apparel-salwar-suits','women-apparel-salwar-suits','Salwar Suits','cat_women-apparel',5,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/salwar-suits',NULL,NOW(),NOW()),
  ('cat_women-apparel-sharara-and-gharara-sets','women-apparel-sharara-and-gharara-sets','Sharara and Gharara Sets','cat_women-apparel',6,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/sharara-and-gharara-sets',NULL,NOW(),NOW()),
  ('cat_women-apparel-tunics','women-apparel-tunics','Tunics','cat_women-apparel',7,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/tunics',NULL,NOW(),NOW()),
  ('cat_women-apparel-dresses','women-apparel-dresses','Dresses','cat_women-apparel',8,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/dresses',NULL,NOW(),NOW()),
  ('cat_women-apparel-blouses','women-apparel-blouses','Blouses','cat_women-apparel',9,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/blouses',NULL,NOW(),NOW()),
  ('cat_women-apparel-jackets','women-apparel-jackets','Jackets','cat_women-apparel',10,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/jackets',NULL,NOW(),NOW()),
  ('cat_women-apparel-skirts','women-apparel-skirts','Skirts','cat_women-apparel',11,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/skirts',NULL,NOW(),NOW()),
  ('cat_women-apparel-pants-and-palazzos','women-apparel-pants-and-palazzos','Pants and Palazzos','cat_women-apparel',12,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/pants-and-palazzos',NULL,NOW(),NOW()),
  ('cat_women-apparel-co-ord-sets','women-apparel-co-ord-sets','Co-ord Sets','cat_women-apparel',13,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/co-ord-sets',NULL,NOW(),NOW()),
  ('cat_women-apparel-loungewear','women-apparel-loungewear','Loungewear','cat_women-apparel',14,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/loungewear',NULL,NOW(),NOW()),
  ('cat_women-apparel-bridal','women-apparel-bridal','Bridal','cat_women-apparel',15,TRUE,FALSE,FALSE,FALSE,3,'women/apparel/bridal',NULL,NOW(),NOW()),
  ('cat_women-outerwear-and-shawls','women-outerwear-and-shawls','Outerwear and Shawls','cat_women',3,TRUE,FALSE,FALSE,FALSE,2,'women/outerwear-and-shawls',NULL,NOW(),NOW()),
  ('cat_women-outerwear-and-shawls-pashmina','women-outerwear-and-shawls-pashmina','Pashmina','cat_women-outerwear-and-shawls',1,TRUE,FALSE,FALSE,FALSE,3,'women/outerwear-and-shawls/pashmina',NULL,NOW(),NOW()),
  ('cat_women-outerwear-and-shawls-kani','women-outerwear-and-shawls-kani','Kani','cat_women-outerwear-and-shawls',2,TRUE,FALSE,FALSE,FALSE,3,'women/outerwear-and-shawls/kani',NULL,NOW(),NOW()),
  ('cat_women-outerwear-and-shawls-sozni','women-outerwear-and-shawls-sozni','Sozni','cat_women-outerwear-and-shawls',3,TRUE,FALSE,FALSE,FALSE,3,'women/outerwear-and-shawls/sozni',NULL,NOW(),NOW()),
  ('cat_women-outerwear-and-shawls-kullu','women-outerwear-and-shawls-kullu','Kullu','cat_women-outerwear-and-shawls',4,TRUE,FALSE,FALSE,FALSE,3,'women/outerwear-and-shawls/kullu',NULL,NOW(),NOW()),
  ('cat_women-outerwear-and-shawls-chamba-rumal','women-outerwear-and-shawls-chamba-rumal','Chamba Rumal','cat_women-outerwear-and-shawls',5,TRUE,FALSE,FALSE,FALSE,3,'women/outerwear-and-shawls/chamba-rumal',NULL,NOW(),NOW()),
  ('cat_women-outerwear-and-shawls-wool-coats','women-outerwear-and-shawls-wool-coats','Wool Coats','cat_women-outerwear-and-shawls',6,TRUE,FALSE,FALSE,FALSE,3,'women/outerwear-and-shawls/wool-coats',NULL,NOW(),NOW()),
  ('cat_women-outerwear-and-shawls-capes','women-outerwear-and-shawls-capes','Capes','cat_women-outerwear-and-shawls',7,TRUE,FALSE,FALSE,FALSE,3,'women/outerwear-and-shawls/capes',NULL,NOW(),NOW()),
  ('cat_women-outerwear-and-shawls-embroidered-jackets','women-outerwear-and-shawls-embroidered-jackets','Embroidered Jackets','cat_women-outerwear-and-shawls',8,TRUE,FALSE,FALSE,FALSE,3,'women/outerwear-and-shawls/embroidered-jackets',NULL,NOW(),NOW()),
  ('cat_women-dupattas-and-stoles','women-dupattas-and-stoles','Dupattas and Stoles','cat_women',4,TRUE,FALSE,FALSE,FALSE,2,'women/dupattas-and-stoles',NULL,NOW(),NOW()),
  ('cat_women-dupattas-and-stoles-phulkari','women-dupattas-and-stoles-phulkari','Phulkari','cat_women-dupattas-and-stoles',1,TRUE,FALSE,FALSE,FALSE,3,'women/dupattas-and-stoles/phulkari',NULL,NOW(),NOW()),
  ('cat_women-dupattas-and-stoles-bandhani','women-dupattas-and-stoles-bandhani','Bandhani','cat_women-dupattas-and-stoles',2,TRUE,FALSE,FALSE,FALSE,3,'women/dupattas-and-stoles/bandhani',NULL,NOW(),NOW()),
  ('cat_women-dupattas-and-stoles-chikankari','women-dupattas-and-stoles-chikankari','Chikankari','cat_women-dupattas-and-stoles',3,TRUE,FALSE,FALSE,FALSE,3,'women/dupattas-and-stoles/chikankari',NULL,NOW(),NOW()),
  ('cat_women-dupattas-and-stoles-banarasi','women-dupattas-and-stoles-banarasi','Banarasi','cat_women-dupattas-and-stoles',4,TRUE,FALSE,FALSE,FALSE,3,'women/dupattas-and-stoles/banarasi',NULL,NOW(),NOW()),
  ('cat_women-dupattas-and-stoles-block-print','women-dupattas-and-stoles-block-print','Block-Print','cat_women-dupattas-and-stoles',5,TRUE,FALSE,FALSE,FALSE,3,'women/dupattas-and-stoles/block-print',NULL,NOW(),NOW()),
  ('cat_women-dupattas-and-stoles-embroidered','women-dupattas-and-stoles-embroidered','Embroidered','cat_women-dupattas-and-stoles',6,TRUE,FALSE,FALSE,FALSE,3,'women/dupattas-and-stoles/embroidered',NULL,NOW(),NOW()),
  ('cat_women-dupattas-and-stoles-plain','women-dupattas-and-stoles-plain','Plain','cat_women-dupattas-and-stoles',7,TRUE,FALSE,FALSE,FALSE,3,'women/dupattas-and-stoles/plain',NULL,NOW(),NOW()),
  ('cat_men','men','Men',NULL,2,TRUE,FALSE,FALSE,FALSE,1,'men',NULL,NOW(),NOW()),
  ('cat_men-apparel','men-apparel','Apparel','cat_men',1,TRUE,FALSE,FALSE,FALSE,2,'men/apparel',NULL,NOW(),NOW()),
  ('cat_men-apparel-kurtas','men-apparel-kurtas','Kurtas','cat_men-apparel',1,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/kurtas',NULL,NOW(),NOW()),
  ('cat_men-apparel-kurta-sets','men-apparel-kurta-sets','Kurta Sets','cat_men-apparel',2,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/kurta-sets',NULL,NOW(),NOW()),
  ('cat_men-apparel-sherwanis','men-apparel-sherwanis','Sherwanis','cat_men-apparel',3,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/sherwanis',NULL,NOW(),NOW()),
  ('cat_men-apparel-nehru-jackets','men-apparel-nehru-jackets','Nehru Jackets','cat_men-apparel',4,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/nehru-jackets',NULL,NOW(),NOW()),
  ('cat_men-apparel-bandhgalas','men-apparel-bandhgalas','Bandhgalas','cat_men-apparel',5,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/bandhgalas',NULL,NOW(),NOW()),
  ('cat_men-apparel-bandi-waistcoats','men-apparel-bandi-waistcoats','Bandi Waistcoats','cat_men-apparel',6,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/bandi-waistcoats',NULL,NOW(),NOW()),
  ('cat_men-apparel-pathani','men-apparel-pathani','Pathani','cat_men-apparel',7,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/pathani',NULL,NOW(),NOW()),
  ('cat_men-apparel-shirts','men-apparel-shirts','Shirts','cat_men-apparel',8,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/shirts',NULL,NOW(),NOW()),
  ('cat_men-apparel-t-shirts','men-apparel-t-shirts','T-shirts','cat_men-apparel',9,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/t-shirts',NULL,NOW(),NOW()),
  ('cat_men-apparel-pants-and-trousers','men-apparel-pants-and-trousers','Pants and Trousers','cat_men-apparel',10,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/pants-and-trousers',NULL,NOW(),NOW()),
  ('cat_men-apparel-pyjamas-and-dhotis','men-apparel-pyjamas-and-dhotis','Pyjamas and Dhotis','cat_men-apparel',11,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/pyjamas-and-dhotis',NULL,NOW(),NOW()),
  ('cat_men-apparel-loungewear','men-apparel-loungewear','Loungewear','cat_men-apparel',12,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/loungewear',NULL,NOW(),NOW()),
  ('cat_men-apparel-groom-wear','men-apparel-groom-wear','Groom Wear','cat_men-apparel',13,TRUE,FALSE,FALSE,FALSE,3,'men/apparel/groom-wear',NULL,NOW(),NOW()),
  ('cat_men-outerwear-and-shawls','men-outerwear-and-shawls','Outerwear and Shawls','cat_men',2,TRUE,FALSE,FALSE,FALSE,2,'men/outerwear-and-shawls',NULL,NOW(),NOW()),
  ('cat_men-outerwear-and-shawls-pashmina','men-outerwear-and-shawls-pashmina','Pashmina','cat_men-outerwear-and-shawls',1,TRUE,FALSE,FALSE,FALSE,3,'men/outerwear-and-shawls/pashmina',NULL,NOW(),NOW()),
  ('cat_men-outerwear-and-shawls-kullu','men-outerwear-and-shawls-kullu','Kullu','cat_men-outerwear-and-shawls',2,TRUE,FALSE,FALSE,FALSE,3,'men/outerwear-and-shawls/kullu',NULL,NOW(),NOW()),
  ('cat_men-outerwear-and-shawls-chamba','men-outerwear-and-shawls-chamba','Chamba','cat_men-outerwear-and-shawls',3,TRUE,FALSE,FALSE,FALSE,3,'men/outerwear-and-shawls/chamba',NULL,NOW(),NOW()),
  ('cat_men-outerwear-and-shawls-wool-coats','men-outerwear-and-shawls-wool-coats','Wool Coats','cat_men-outerwear-and-shawls',4,TRUE,FALSE,FALSE,FALSE,3,'men/outerwear-and-shawls/wool-coats',NULL,NOW(),NOW()),
  ('cat_men-outerwear-and-shawls-capes','men-outerwear-and-shawls-capes','Capes','cat_men-outerwear-and-shawls',5,TRUE,FALSE,FALSE,FALSE,3,'men/outerwear-and-shawls/capes',NULL,NOW(),NOW()),
  ('cat_men-outerwear-and-shawls-bandi-jackets','men-outerwear-and-shawls-bandi-jackets','Bandi Jackets','cat_men-outerwear-and-shawls',6,TRUE,FALSE,FALSE,FALSE,3,'men/outerwear-and-shawls/bandi-jackets',NULL,NOW(),NOW()),
  ('cat_accessories','accessories','Accessories',NULL,3,TRUE,FALSE,FALSE,FALSE,1,'accessories',NULL,NOW(),NOW()),
  ('cat_accessories-jewellery','accessories-jewellery','Jewellery','cat_accessories',1,TRUE,FALSE,FALSE,FALSE,2,'accessories/jewellery','women',NOW(),NOW()),
  ('cat_accessories-jewellery-necklaces','accessories-jewellery-necklaces','Necklaces','cat_accessories-jewellery',1,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/necklaces','women',NOW(),NOW()),
  ('cat_accessories-jewellery-earrings','accessories-jewellery-earrings','Earrings','cat_accessories-jewellery',2,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/earrings','women',NOW(),NOW()),
  ('cat_accessories-jewellery-bangles-and-cuffs','accessories-jewellery-bangles-and-cuffs','Bangles and Cuffs','cat_accessories-jewellery',3,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/bangles-and-cuffs','women',NOW(),NOW()),
  ('cat_accessories-jewellery-bracelets','accessories-jewellery-bracelets','Bracelets','cat_accessories-jewellery',4,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/bracelets','women',NOW(),NOW()),
  ('cat_accessories-jewellery-rings','accessories-jewellery-rings','Rings','cat_accessories-jewellery',5,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/rings','women',NOW(),NOW()),
  ('cat_accessories-jewellery-maang-tikka','accessories-jewellery-maang-tikka','Maang-tikka','cat_accessories-jewellery',6,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/maang-tikka','women',NOW(),NOW()),
  ('cat_accessories-jewellery-nose-pins','accessories-jewellery-nose-pins','Nose Pins','cat_accessories-jewellery',7,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/nose-pins','women',NOW(),NOW()),
  ('cat_accessories-jewellery-anklets','accessories-jewellery-anklets','Anklets','cat_accessories-jewellery',8,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/anklets','women',NOW(),NOW()),
  ('cat_accessories-jewellery-toe-rings','accessories-jewellery-toe-rings','Toe Rings','cat_accessories-jewellery',9,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/toe-rings','women',NOW(),NOW()),
  ('cat_accessories-jewellery-hair-accessories','accessories-jewellery-hair-accessories','Hair Accessories','cat_accessories-jewellery',10,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/hair-accessories','women',NOW(),NOW()),
  ('cat_accessories-jewellery-jewellery-sets','accessories-jewellery-jewellery-sets','Jewellery Sets','cat_accessories-jewellery',11,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/jewellery-sets','women',NOW(),NOW()),
  ('cat_accessories-jewellery-bridal-sets','accessories-jewellery-bridal-sets','Bridal Sets','cat_accessories-jewellery',12,TRUE,FALSE,FALSE,FALSE,3,'accessories/jewellery/bridal-sets','women',NOW(),NOW()),
  ('cat_accessories-bags-and-purses','accessories-bags-and-purses','Bags and Purses','cat_accessories',2,TRUE,FALSE,FALSE,FALSE,2,'accessories/bags-and-purses','unisex',NOW(),NOW()),
  ('cat_accessories-bags-and-purses-clutches','accessories-bags-and-purses-clutches','Clutches','cat_accessories-bags-and-purses',1,TRUE,FALSE,FALSE,FALSE,3,'accessories/bags-and-purses/clutches','unisex',NOW(),NOW()),
  ('cat_accessories-bags-and-purses-potlis','accessories-bags-and-purses-potlis','Potlis','cat_accessories-bags-and-purses',2,TRUE,FALSE,FALSE,FALSE,3,'accessories/bags-and-purses/potlis','unisex',NOW(),NOW()),
  ('cat_accessories-bags-and-purses-tote-bags','accessories-bags-and-purses-tote-bags','Tote Bags','cat_accessories-bags-and-purses',3,TRUE,FALSE,FALSE,FALSE,3,'accessories/bags-and-purses/tote-bags','unisex',NOW(),NOW()),
  ('cat_accessories-bags-and-purses-sling-bags','accessories-bags-and-purses-sling-bags','Sling Bags','cat_accessories-bags-and-purses',4,TRUE,FALSE,FALSE,FALSE,3,'accessories/bags-and-purses/sling-bags','unisex',NOW(),NOW()),
  ('cat_accessories-bags-and-purses-handbags','accessories-bags-and-purses-handbags','Handbags','cat_accessories-bags-and-purses',5,TRUE,FALSE,FALSE,FALSE,3,'accessories/bags-and-purses/handbags','unisex',NOW(),NOW()),
  ('cat_accessories-bags-and-purses-wallets','accessories-bags-and-purses-wallets','Wallets','cat_accessories-bags-and-purses',6,TRUE,FALSE,FALSE,FALSE,3,'accessories/bags-and-purses/wallets','unisex',NOW(),NOW()),
  ('cat_accessories-bags-and-purses-coin-purses','accessories-bags-and-purses-coin-purses','Coin Purses','cat_accessories-bags-and-purses',7,TRUE,FALSE,FALSE,FALSE,3,'accessories/bags-and-purses/coin-purses','unisex',NOW(),NOW()),
  ('cat_accessories-footwear','accessories-footwear','Footwear','cat_accessories',3,TRUE,FALSE,FALSE,FALSE,2,'accessories/footwear','unisex',NOW(),NOW()),
  ('cat_accessories-footwear-juttis','accessories-footwear-juttis','Juttis','cat_accessories-footwear',1,TRUE,FALSE,FALSE,FALSE,3,'accessories/footwear/juttis','unisex',NOW(),NOW()),
  ('cat_accessories-footwear-mojaris','accessories-footwear-mojaris','Mojaris','cat_accessories-footwear',2,TRUE,FALSE,FALSE,FALSE,3,'accessories/footwear/mojaris','unisex',NOW(),NOW()),
  ('cat_accessories-footwear-kolhapuris','accessories-footwear-kolhapuris','Kolhapuris','cat_accessories-footwear',3,TRUE,FALSE,FALSE,FALSE,3,'accessories/footwear/kolhapuris','unisex',NOW(),NOW()),
  ('cat_accessories-footwear-sandals','accessories-footwear-sandals','Sandals','cat_accessories-footwear',4,TRUE,FALSE,FALSE,FALSE,3,'accessories/footwear/sandals','unisex',NOW(),NOW()),
  ('cat_accessories-footwear-heels','accessories-footwear-heels','Heels','cat_accessories-footwear',5,TRUE,FALSE,FALSE,FALSE,3,'accessories/footwear/heels','unisex',NOW(),NOW()),
  ('cat_accessories-footwear-flats','accessories-footwear-flats','Flats','cat_accessories-footwear',6,TRUE,FALSE,FALSE,FALSE,3,'accessories/footwear/flats','unisex',NOW(),NOW()),
  ('cat_accessories-footwear-loafers','accessories-footwear-loafers','Loafers','cat_accessories-footwear',7,TRUE,FALSE,FALSE,FALSE,3,'accessories/footwear/loafers','unisex',NOW(),NOW()),
  ('cat_accessories-belts-and-ties','accessories-belts-and-ties','Belts and Ties','cat_accessories',4,TRUE,FALSE,FALSE,FALSE,2,'accessories/belts-and-ties','men',NOW(),NOW()),
  ('cat_accessories-belts-and-ties-belts','accessories-belts-and-ties-belts','Belts','cat_accessories-belts-and-ties',1,TRUE,FALSE,FALSE,FALSE,3,'accessories/belts-and-ties/belts','men',NOW(),NOW()),
  ('cat_accessories-belts-and-ties-ties','accessories-belts-and-ties-ties','Ties','cat_accessories-belts-and-ties',2,TRUE,FALSE,FALSE,FALSE,3,'accessories/belts-and-ties/ties','men',NOW(),NOW()),
  ('cat_accessories-belts-and-ties-tie-pins','accessories-belts-and-ties-tie-pins','Tie-pins','cat_accessories-belts-and-ties',3,TRUE,FALSE,FALSE,FALSE,3,'accessories/belts-and-ties/tie-pins','men',NOW(),NOW()),
  ('cat_accessories-belts-and-ties-suspenders','accessories-belts-and-ties-suspenders','Suspenders','cat_accessories-belts-and-ties',4,TRUE,FALSE,FALSE,FALSE,3,'accessories/belts-and-ties/suspenders','men',NOW(),NOW()),
  ('cat_accessories-cuff-links-and-lapel','accessories-cuff-links-and-lapel','Cuff Links and Lapel','cat_accessories',5,TRUE,FALSE,FALSE,FALSE,2,'accessories/cuff-links-and-lapel','men',NOW(),NOW()),
  ('cat_accessories-cuff-links-and-lapel-cuff-links','accessories-cuff-links-and-lapel-cuff-links','Cuff Links','cat_accessories-cuff-links-and-lapel',1,TRUE,FALSE,FALSE,FALSE,3,'accessories/cuff-links-and-lapel/cuff-links','men',NOW(),NOW()),
  ('cat_accessories-cuff-links-and-lapel-pocket-squares','accessories-cuff-links-and-lapel-pocket-squares','Pocket Squares','cat_accessories-cuff-links-and-lapel',2,TRUE,FALSE,FALSE,FALSE,3,'accessories/cuff-links-and-lapel/pocket-squares','men',NOW(),NOW()),
  ('cat_accessories-cuff-links-and-lapel-lapel-pins','accessories-cuff-links-and-lapel-lapel-pins','Lapel Pins','cat_accessories-cuff-links-and-lapel',3,TRUE,FALSE,FALSE,FALSE,3,'accessories/cuff-links-and-lapel/lapel-pins','men',NOW(),NOW()),
  ('cat_accessories-cuff-links-and-lapel-tie-bars','accessories-cuff-links-and-lapel-tie-bars','Tie Bars','cat_accessories-cuff-links-and-lapel',4,TRUE,FALSE,FALSE,FALSE,3,'accessories/cuff-links-and-lapel/tie-bars','men',NOW(),NOW()),
  ('cat_accessories-eyewear','accessories-eyewear','Eyewear','cat_accessories',6,TRUE,FALSE,FALSE,FALSE,2,'accessories/eyewear','unisex',NOW(),NOW()),
  ('cat_accessories-eyewear-sunglasses','accessories-eyewear-sunglasses','Sunglasses','cat_accessories-eyewear',1,TRUE,FALSE,FALSE,FALSE,3,'accessories/eyewear/sunglasses','unisex',NOW(),NOW()),
  ('cat_accessories-eyewear-optical-frames','accessories-eyewear-optical-frames','Optical Frames','cat_accessories-eyewear',2,TRUE,FALSE,FALSE,FALSE,3,'accessories/eyewear/optical-frames','unisex',NOW(),NOW()),
  ('cat_accessories-hair-and-headwear','accessories-hair-and-headwear','Hair and Headwear','cat_accessories',7,TRUE,FALSE,FALSE,FALSE,2,'accessories/hair-and-headwear','unisex',NOW(),NOW()),
  ('cat_accessories-hair-and-headwear-parandi','accessories-hair-and-headwear-parandi','Parandi','cat_accessories-hair-and-headwear',1,TRUE,FALSE,FALSE,FALSE,3,'accessories/hair-and-headwear/parandi','unisex',NOW(),NOW()),
  ('cat_accessories-hair-and-headwear-hair-sticks','accessories-hair-and-headwear-hair-sticks','Hair Sticks','cat_accessories-hair-and-headwear',2,TRUE,FALSE,FALSE,FALSE,3,'accessories/hair-and-headwear/hair-sticks','unisex',NOW(),NOW()),
  ('cat_accessories-hair-and-headwear-headbands','accessories-hair-and-headwear-headbands','Headbands','cat_accessories-hair-and-headwear',3,TRUE,FALSE,FALSE,FALSE,3,'accessories/hair-and-headwear/headbands','unisex',NOW(),NOW()),
  ('cat_accessories-hair-and-headwear-pagdis','accessories-hair-and-headwear-pagdis','Pagdis','cat_accessories-hair-and-headwear',4,TRUE,FALSE,FALSE,FALSE,3,'accessories/hair-and-headwear/pagdis','unisex',NOW(),NOW()),
  ('cat_accessories-hair-and-headwear-turban-pieces','accessories-hair-and-headwear-turban-pieces','Turban Pieces','cat_accessories-hair-and-headwear',5,TRUE,FALSE,FALSE,FALSE,3,'accessories/hair-and-headwear/turban-pieces','unisex',NOW(),NOW()),
  ('cat_accessories-personal-care','accessories-personal-care','Personal Care','cat_accessories',8,TRUE,FALSE,FALSE,FALSE,2,'accessories/personal-care','unisex',NOW(),NOW()),
  ('cat_accessories-personal-care-skin','accessories-personal-care-skin','Skin','cat_accessories-personal-care',1,TRUE,FALSE,FALSE,FALSE,3,'accessories/personal-care/skin','unisex',NOW(),NOW()),
  ('cat_accessories-personal-care-hair','accessories-personal-care-hair','Hair','cat_accessories-personal-care',2,TRUE,FALSE,FALSE,FALSE,3,'accessories/personal-care/hair','unisex',NOW(),NOW()),
  ('cat_accessories-personal-care-bath-and-body','accessories-personal-care-bath-and-body','Bath and Body','cat_accessories-personal-care',3,TRUE,FALSE,FALSE,FALSE,3,'accessories/personal-care/bath-and-body','unisex',NOW(),NOW()),
  ('cat_accessories-personal-care-lip-care','accessories-personal-care-lip-care','Lip Care','cat_accessories-personal-care',4,TRUE,FALSE,FALSE,FALSE,3,'accessories/personal-care/lip-care','unisex',NOW(),NOW()),
  ('cat_accessories-personal-care-shaving-and-grooming-kits','accessories-personal-care-shaving-and-grooming-kits','Shaving and Grooming Kits','cat_accessories-personal-care',5,TRUE,FALSE,FALSE,FALSE,3,'accessories/personal-care/shaving-and-grooming-kits','unisex',NOW(),NOW()),
  ('cat_accessories-personal-care-wellness-tonics','accessories-personal-care-wellness-tonics','Wellness Tonics','cat_accessories-personal-care',6,TRUE,FALSE,FALSE,FALSE,3,'accessories/personal-care/wellness-tonics','unisex',NOW(),NOW()),
  ('cat_home','home','Home',NULL,4,TRUE,FALSE,FALSE,FALSE,1,'home',NULL,NOW(),NOW()),
  ('cat_home-furniture','home-furniture','Furniture','cat_home',1,TRUE,FALSE,FALSE,FALSE,2,'home/furniture',NULL,NOW(),NOW()),
  ('cat_home-furniture-sofas','home-furniture-sofas','Sofas','cat_home-furniture',1,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/sofas',NULL,NOW(),NOW()),
  ('cat_home-furniture-chairs','home-furniture-chairs','Chairs','cat_home-furniture',2,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/chairs',NULL,NOW(),NOW()),
  ('cat_home-furniture-beds','home-furniture-beds','Beds','cat_home-furniture',3,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/beds',NULL,NOW(),NOW()),
  ('cat_home-furniture-side-tables','home-furniture-side-tables','Side Tables','cat_home-furniture',4,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/side-tables',NULL,NOW(),NOW()),
  ('cat_home-furniture-coffee-tables','home-furniture-coffee-tables','Coffee Tables','cat_home-furniture',5,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/coffee-tables',NULL,NOW(),NOW()),
  ('cat_home-furniture-dining-tables','home-furniture-dining-tables','Dining Tables','cat_home-furniture',6,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/dining-tables',NULL,NOW(),NOW()),
  ('cat_home-furniture-dining-chairs','home-furniture-dining-chairs','Dining Chairs','cat_home-furniture',7,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/dining-chairs',NULL,NOW(),NOW()),
  ('cat_home-furniture-cabinets','home-furniture-cabinets','Cabinets','cat_home-furniture',8,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/cabinets',NULL,NOW(),NOW()),
  ('cat_home-furniture-shelves','home-furniture-shelves','Shelves','cat_home-furniture',9,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/shelves',NULL,NOW(),NOW()),
  ('cat_home-furniture-wardrobes','home-furniture-wardrobes','Wardrobes','cat_home-furniture',10,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/wardrobes',NULL,NOW(),NOW()),
  ('cat_home-furniture-consoles','home-furniture-consoles','Consoles','cat_home-furniture',11,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/consoles',NULL,NOW(),NOW()),
  ('cat_home-furniture-mirrors','home-furniture-mirrors','Mirrors','cat_home-furniture',12,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/mirrors',NULL,NOW(),NOW()),
  ('cat_home-furniture-trunks','home-furniture-trunks','Trunks','cat_home-furniture',13,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/trunks',NULL,NOW(),NOW()),
  ('cat_home-furniture-stools','home-furniture-stools','Stools','cat_home-furniture',14,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/stools',NULL,NOW(),NOW()),
  ('cat_home-furniture-ottomans','home-furniture-ottomans','Ottomans','cat_home-furniture',15,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/ottomans',NULL,NOW(),NOW()),
  ('cat_home-furniture-outdoor-furniture','home-furniture-outdoor-furniture','Outdoor Furniture','cat_home-furniture',16,TRUE,FALSE,FALSE,FALSE,3,'home/furniture/outdoor-furniture',NULL,NOW(),NOW()),
  ('cat_home-lighting-decorative','home-lighting-decorative','Lighting Decorative','cat_home',2,TRUE,FALSE,FALSE,FALSE,2,'home/lighting-decorative',NULL,NOW(),NOW()),
  ('cat_home-lighting-decorative-floor-lamps','home-lighting-decorative-floor-lamps','Floor Lamps','cat_home-lighting-decorative',1,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-decorative/floor-lamps',NULL,NOW(),NOW()),
  ('cat_home-lighting-decorative-table-lamps','home-lighting-decorative-table-lamps','Table Lamps','cat_home-lighting-decorative',2,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-decorative/table-lamps',NULL,NOW(),NOW()),
  ('cat_home-lighting-decorative-pendant-lamps','home-lighting-decorative-pendant-lamps','Pendant Lamps','cat_home-lighting-decorative',3,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-decorative/pendant-lamps',NULL,NOW(),NOW()),
  ('cat_home-lighting-decorative-wall-sconces','home-lighting-decorative-wall-sconces','Wall Sconces','cat_home-lighting-decorative',4,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-decorative/wall-sconces',NULL,NOW(),NOW()),
  ('cat_home-lighting-decorative-lanterns','home-lighting-decorative-lanterns','Lanterns','cat_home-lighting-decorative',5,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-decorative/lanterns',NULL,NOW(),NOW()),
  ('cat_home-lighting-decorative-lampshades','home-lighting-decorative-lampshades','Lampshades','cat_home-lighting-decorative',6,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-decorative/lampshades',NULL,NOW(),NOW()),
  ('cat_home-lighting-decorative-candle-stands','home-lighting-decorative-candle-stands','Candle Stands','cat_home-lighting-decorative',7,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-decorative/candle-stands',NULL,NOW(),NOW()),
  ('cat_home-lighting-decorative-diyas','home-lighting-decorative-diyas','Diyas','cat_home-lighting-decorative',8,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-decorative/diyas',NULL,NOW(),NOW()),
  ('cat_home-lighting-decorative-chandeliers','home-lighting-decorative-chandeliers','Chandeliers','cat_home-lighting-decorative',9,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-decorative/chandeliers',NULL,NOW(),NOW()),
  ('cat_home-lighting-architectural','home-lighting-architectural','Lighting Architectural','cat_home',3,TRUE,FALSE,FALSE,FALSE,2,'home/lighting-architectural',NULL,NOW(),NOW()),
  ('cat_home-lighting-architectural-recessed','home-lighting-architectural-recessed','Recessed','cat_home-lighting-architectural',1,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-architectural/recessed',NULL,NOW(),NOW()),
  ('cat_home-lighting-architectural-track-lighting','home-lighting-architectural-track-lighting','Track Lighting','cat_home-lighting-architectural',2,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-architectural/track-lighting',NULL,NOW(),NOW()),
  ('cat_home-lighting-architectural-smart-bulbs','home-lighting-architectural-smart-bulbs','Smart Bulbs','cat_home-lighting-architectural',3,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-architectural/smart-bulbs',NULL,NOW(),NOW()),
  ('cat_home-lighting-architectural-dimmers-and-switches','home-lighting-architectural-dimmers-and-switches','Dimmers and Switches','cat_home-lighting-architectural',4,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-architectural/dimmers-and-switches',NULL,NOW(),NOW()),
  ('cat_home-lighting-architectural-outdoor-lighting','home-lighting-architectural-outdoor-lighting','Outdoor Lighting','cat_home-lighting-architectural',5,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-architectural/outdoor-lighting',NULL,NOW(),NOW()),
  ('cat_home-lighting-architectural-garden-lights','home-lighting-architectural-garden-lights','Garden Lights','cat_home-lighting-architectural',6,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-architectural/garden-lights',NULL,NOW(),NOW()),
  ('cat_home-lighting-architectural-wall-wash','home-lighting-architectural-wall-wash','Wall Wash','cat_home-lighting-architectural',7,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-architectural/wall-wash',NULL,NOW(),NOW()),
  ('cat_home-lighting-architectural-strip-lighting','home-lighting-architectural-strip-lighting','Strip Lighting','cat_home-lighting-architectural',8,TRUE,FALSE,FALSE,FALSE,3,'home/lighting-architectural/strip-lighting',NULL,NOW(),NOW()),
  ('cat_home-linens-bed','home-linens-bed','Linens Bed','cat_home',4,TRUE,FALSE,FALSE,FALSE,2,'home/linens-bed',NULL,NOW(),NOW()),
  ('cat_home-linens-bed-bedsheets','home-linens-bed-bedsheets','Bedsheets','cat_home-linens-bed',1,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bed/bedsheets',NULL,NOW(),NOW()),
  ('cat_home-linens-bed-duvet-covers','home-linens-bed-duvet-covers','Duvet Covers','cat_home-linens-bed',2,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bed/duvet-covers',NULL,NOW(),NOW()),
  ('cat_home-linens-bed-dohars','home-linens-bed-dohars','Dohars','cat_home-linens-bed',3,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bed/dohars',NULL,NOW(),NOW()),
  ('cat_home-linens-bed-quilts','home-linens-bed-quilts','Quilts','cat_home-linens-bed',4,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bed/quilts',NULL,NOW(),NOW()),
  ('cat_home-linens-bed-razais','home-linens-bed-razais','Razais','cat_home-linens-bed',5,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bed/razais',NULL,NOW(),NOW()),
  ('cat_home-linens-bed-throws','home-linens-bed-throws','Throws','cat_home-linens-bed',6,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bed/throws',NULL,NOW(),NOW()),
  ('cat_home-linens-bed-pillow-covers','home-linens-bed-pillow-covers','Pillow Covers','cat_home-linens-bed',7,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bed/pillow-covers',NULL,NOW(),NOW()),
  ('cat_home-linens-bed-bolster-covers','home-linens-bed-bolster-covers','Bolster Covers','cat_home-linens-bed',8,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bed/bolster-covers',NULL,NOW(),NOW()),
  ('cat_home-linens-bed-bed-runners','home-linens-bed-bed-runners','Bed Runners','cat_home-linens-bed',9,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bed/bed-runners',NULL,NOW(),NOW()),
  ('cat_home-linens-bath','home-linens-bath','Linens Bath','cat_home',5,TRUE,FALSE,FALSE,FALSE,2,'home/linens-bath',NULL,NOW(),NOW()),
  ('cat_home-linens-bath-towels','home-linens-bath-towels','Towels','cat_home-linens-bath',1,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bath/towels',NULL,NOW(),NOW()),
  ('cat_home-linens-bath-bath-mats','home-linens-bath-bath-mats','Bath Mats','cat_home-linens-bath',2,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bath/bath-mats',NULL,NOW(),NOW()),
  ('cat_home-linens-bath-bathrobes','home-linens-bath-bathrobes','Bathrobes','cat_home-linens-bath',3,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bath/bathrobes',NULL,NOW(),NOW()),
  ('cat_home-linens-bath-shower-curtains','home-linens-bath-shower-curtains','Shower Curtains','cat_home-linens-bath',4,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bath/shower-curtains',NULL,NOW(),NOW()),
  ('cat_home-linens-bath-hammam-sheets','home-linens-bath-hammam-sheets','Hammam Sheets','cat_home-linens-bath',5,TRUE,FALSE,FALSE,FALSE,3,'home/linens-bath/hammam-sheets',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings','home-soft-furnishings','Soft Furnishings','cat_home',6,TRUE,FALSE,FALSE,FALSE,2,'home/soft-furnishings',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings-cushions','home-soft-furnishings-cushions','Cushions','cat_home-soft-furnishings',1,TRUE,FALSE,FALSE,FALSE,3,'home/soft-furnishings/cushions',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings-cushion-covers','home-soft-furnishings-cushion-covers','Cushion Covers','cat_home-soft-furnishings',2,TRUE,FALSE,FALSE,FALSE,3,'home/soft-furnishings/cushion-covers',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings-floor-cushions','home-soft-furnishings-floor-cushions','Floor Cushions','cat_home-soft-furnishings',3,TRUE,FALSE,FALSE,FALSE,3,'home/soft-furnishings/floor-cushions',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings-curtains','home-soft-furnishings-curtains','Curtains','cat_home-soft-furnishings',4,TRUE,FALSE,FALSE,FALSE,3,'home/soft-furnishings/curtains',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings-runners','home-soft-furnishings-runners','Runners','cat_home-soft-furnishings',5,TRUE,FALSE,FALSE,FALSE,3,'home/soft-furnishings/runners',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings-durries','home-soft-furnishings-durries','Durries','cat_home-soft-furnishings',6,TRUE,FALSE,FALSE,FALSE,3,'home/soft-furnishings/durries',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings-rugs','home-soft-furnishings-rugs','Rugs','cat_home-soft-furnishings',7,TRUE,FALSE,FALSE,FALSE,3,'home/soft-furnishings/rugs',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings-carpets','home-soft-furnishings-carpets','Carpets','cat_home-soft-furnishings',8,TRUE,FALSE,FALSE,FALSE,3,'home/soft-furnishings/carpets',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings-tapestries','home-soft-furnishings-tapestries','Tapestries','cat_home-soft-furnishings',9,TRUE,FALSE,FALSE,FALSE,3,'home/soft-furnishings/tapestries',NULL,NOW(),NOW()),
  ('cat_home-soft-furnishings-pouffes','home-soft-furnishings-pouffes','Pouffes','cat_home-soft-furnishings',10,TRUE,FALSE,FALSE,FALSE,3,'home/soft-furnishings/pouffes',NULL,NOW(),NOW()),
  ('cat_home-bath','home-bath','Bath','cat_home',7,TRUE,FALSE,FALSE,FALSE,2,'home/bath',NULL,NOW(),NOW()),
  ('cat_home-bath-hammam-bowls','home-bath-hammam-bowls','Hammam Bowls','cat_home-bath',1,TRUE,FALSE,FALSE,FALSE,3,'home/bath/hammam-bowls',NULL,NOW(),NOW()),
  ('cat_home-bath-soap-dishes','home-bath-soap-dishes','Soap Dishes','cat_home-bath',2,TRUE,FALSE,FALSE,FALSE,3,'home/bath/soap-dishes',NULL,NOW(),NOW()),
  ('cat_home-bath-dispensers','home-bath-dispensers','Dispensers','cat_home-bath',3,TRUE,FALSE,FALSE,FALSE,3,'home/bath/dispensers',NULL,NOW(),NOW()),
  ('cat_home-bath-storage','home-bath-storage','Storage','cat_home-bath',4,TRUE,FALSE,FALSE,FALSE,3,'home/bath/storage',NULL,NOW(),NOW()),
  ('cat_home-bath-bathroom-mirrors','home-bath-bathroom-mirrors','Bathroom Mirrors','cat_home-bath',5,TRUE,FALSE,FALSE,FALSE,3,'home/bath/bathroom-mirrors',NULL,NOW(),NOW()),
  ('cat_home-bath-bath-accessories','home-bath-bath-accessories','Bath Accessories','cat_home-bath',6,TRUE,FALSE,FALSE,FALSE,3,'home/bath/bath-accessories',NULL,NOW(),NOW()),
  ('cat_home-kitchen','home-kitchen','Kitchen','cat_home',8,TRUE,FALSE,FALSE,FALSE,2,'home/kitchen',NULL,NOW(),NOW()),
  ('cat_home-kitchen-brass-cookware','home-kitchen-brass-cookware','Brass Cookware','cat_home-kitchen',1,TRUE,FALSE,FALSE,FALSE,3,'home/kitchen/brass-cookware',NULL,NOW(),NOW()),
  ('cat_home-kitchen-copper-cookware','home-kitchen-copper-cookware','Copper Cookware','cat_home-kitchen',2,TRUE,FALSE,FALSE,FALSE,3,'home/kitchen/copper-cookware',NULL,NOW(),NOW()),
  ('cat_home-kitchen-iron-cookware','home-kitchen-iron-cookware','Iron Cookware','cat_home-kitchen',3,TRUE,FALSE,FALSE,FALSE,3,'home/kitchen/iron-cookware',NULL,NOW(),NOW()),
  ('cat_home-kitchen-clay-cookware','home-kitchen-clay-cookware','Clay Cookware','cat_home-kitchen',4,TRUE,FALSE,FALSE,FALSE,3,'home/kitchen/clay-cookware',NULL,NOW(),NOW()),
  ('cat_home-kitchen-bakeware','home-kitchen-bakeware','Bakeware','cat_home-kitchen',5,TRUE,FALSE,FALSE,FALSE,3,'home/kitchen/bakeware',NULL,NOW(),NOW()),
  ('cat_home-kitchen-pots-and-pans','home-kitchen-pots-and-pans','Pots and Pans','cat_home-kitchen',6,TRUE,FALSE,FALSE,FALSE,3,'home/kitchen/pots-and-pans',NULL,NOW(),NOW()),
  ('cat_home-kitchen-tawas','home-kitchen-tawas','Tawas','cat_home-kitchen',7,TRUE,FALSE,FALSE,FALSE,3,'home/kitchen/tawas',NULL,NOW(),NOW()),
  ('cat_home-kitchen-kitchen-tools','home-kitchen-kitchen-tools','Kitchen Tools','cat_home-kitchen',8,TRUE,FALSE,FALSE,FALSE,3,'home/kitchen/kitchen-tools',NULL,NOW(),NOW()),
  ('cat_home-kitchen-storage-jars','home-kitchen-storage-jars','Storage Jars','cat_home-kitchen',9,TRUE,FALSE,FALSE,FALSE,3,'home/kitchen/storage-jars',NULL,NOW(),NOW()),
  ('cat_home-kitchen-kitchen-linen','home-kitchen-kitchen-linen','Kitchen Linen','cat_home-kitchen',10,TRUE,FALSE,FALSE,FALSE,3,'home/kitchen/kitchen-linen',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware','home-dining-and-tableware','Dining and Tableware','cat_home',9,TRUE,FALSE,FALSE,FALSE,2,'home/dining-and-tableware',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-dinner-plates','home-dining-and-tableware-dinner-plates','Dinner Plates','cat_home-dining-and-tableware',1,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/dinner-plates',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-bowls','home-dining-and-tableware-bowls','Bowls','cat_home-dining-and-tableware',2,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/bowls',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-platters','home-dining-and-tableware-platters','Platters','cat_home-dining-and-tableware',3,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/platters',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-cups-and-saucers','home-dining-and-tableware-cups-and-saucers','Cups and Saucers','cat_home-dining-and-tableware',4,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/cups-and-saucers',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-mugs','home-dining-and-tableware-mugs','Mugs','cat_home-dining-and-tableware',5,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/mugs',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-tumblers','home-dining-and-tableware-tumblers','Tumblers','cat_home-dining-and-tableware',6,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/tumblers',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-pitchers','home-dining-and-tableware-pitchers','Pitchers','cat_home-dining-and-tableware',7,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/pitchers',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-cutlery-sets','home-dining-and-tableware-cutlery-sets','Cutlery Sets','cat_home-dining-and-tableware',8,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/cutlery-sets',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-serveware','home-dining-and-tableware-serveware','Serveware','cat_home-dining-and-tableware',9,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/serveware',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-trivets','home-dining-and-tableware-trivets','Trivets','cat_home-dining-and-tableware',10,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/trivets',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-bone-china','home-dining-and-tableware-bone-china','Bone China','cat_home-dining-and-tableware',11,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/bone-china',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-stoneware','home-dining-and-tableware-stoneware','Stoneware','cat_home-dining-and-tableware',12,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/stoneware',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-terracotta','home-dining-and-tableware-terracotta','Terracotta','cat_home-dining-and-tableware',13,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/terracotta',NULL,NOW(),NOW()),
  ('cat_home-dining-and-tableware-glassware','home-dining-and-tableware-glassware','Glassware','cat_home-dining-and-tableware',14,TRUE,FALSE,FALSE,FALSE,3,'home/dining-and-tableware/glassware',NULL,NOW(),NOW()),
  ('cat_home-bar','home-bar','Bar','cat_home',10,TRUE,FALSE,FALSE,FALSE,2,'home/bar',NULL,NOW(),NOW()),
  ('cat_home-bar-trolleys','home-bar-trolleys','Trolleys','cat_home-bar',1,TRUE,FALSE,FALSE,FALSE,3,'home/bar/trolleys',NULL,NOW(),NOW()),
  ('cat_home-bar-bar-cabinets','home-bar-bar-cabinets','Bar Cabinets','cat_home-bar',2,TRUE,FALSE,FALSE,FALSE,3,'home/bar/bar-cabinets',NULL,NOW(),NOW()),
  ('cat_home-bar-wine-racks','home-bar-wine-racks','Wine Racks','cat_home-bar',3,TRUE,FALSE,FALSE,FALSE,3,'home/bar/wine-racks',NULL,NOW(),NOW()),
  ('cat_home-bar-bar-kits','home-bar-bar-kits','Bar Kits','cat_home-bar',4,TRUE,FALSE,FALSE,FALSE,3,'home/bar/bar-kits',NULL,NOW(),NOW()),
  ('cat_home-bar-decanters','home-bar-decanters','Decanters','cat_home-bar',5,TRUE,FALSE,FALSE,FALSE,3,'home/bar/decanters',NULL,NOW(),NOW()),
  ('cat_home-bar-wine-glasses','home-bar-wine-glasses','Wine Glasses','cat_home-bar',6,TRUE,FALSE,FALSE,FALSE,3,'home/bar/wine-glasses',NULL,NOW(),NOW()),
  ('cat_home-bar-whisky-glasses','home-bar-whisky-glasses','Whisky Glasses','cat_home-bar',7,TRUE,FALSE,FALSE,FALSE,3,'home/bar/whisky-glasses',NULL,NOW(),NOW()),
  ('cat_home-bar-cocktail-tools','home-bar-cocktail-tools','Cocktail Tools','cat_home-bar',8,TRUE,FALSE,FALSE,FALSE,3,'home/bar/cocktail-tools',NULL,NOW(),NOW()),
  ('cat_home-bar-coasters','home-bar-coasters','Coasters','cat_home-bar',9,TRUE,FALSE,FALSE,FALSE,3,'home/bar/coasters',NULL,NOW(),NOW()),
  ('cat_home-bar-ice-buckets','home-bar-ice-buckets','Ice Buckets','cat_home-bar',10,TRUE,FALSE,FALSE,FALSE,3,'home/bar/ice-buckets',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents','home-decor-and-accents','Decor and Accents','cat_home',11,TRUE,FALSE,FALSE,FALSE,2,'home/decor-and-accents',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-vases','home-decor-and-accents-vases','Vases','cat_home-decor-and-accents',1,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/vases',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-photo-frames','home-decor-and-accents-photo-frames','Photo Frames','cat_home-decor-and-accents',2,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/photo-frames',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-wall-art','home-decor-and-accents-wall-art','Wall Art','cat_home-decor-and-accents',3,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/wall-art',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-wall-plates','home-decor-and-accents-wall-plates','Wall Plates','cat_home-decor-and-accents',4,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/wall-plates',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-sculptures','home-decor-and-accents-sculptures','Sculptures','cat_home-decor-and-accents',5,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/sculptures',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-bookends','home-decor-and-accents-bookends','Bookends','cat_home-decor-and-accents',6,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/bookends',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-clocks','home-decor-and-accents-clocks','Clocks','cat_home-decor-and-accents',7,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/clocks',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-candles','home-decor-and-accents-candles','Candles','cat_home-decor-and-accents',8,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/candles',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-incense','home-decor-and-accents-incense','Incense','cat_home-decor-and-accents',9,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/incense',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-diffusers','home-decor-and-accents-diffusers','Diffusers','cat_home-decor-and-accents',10,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/diffusers',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-pichhwai','home-decor-and-accents-pichhwai','Pichhwai','cat_home-decor-and-accents',11,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/pichhwai',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-tanjore','home-decor-and-accents-tanjore','Tanjore','cat_home-decor-and-accents',12,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/tanjore',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-madhubani','home-decor-and-accents-madhubani','Madhubani','cat_home-decor-and-accents',13,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/madhubani',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-pattachitra','home-decor-and-accents-pattachitra','Pattachitra','cat_home-decor-and-accents',14,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/pattachitra',NULL,NOW(),NOW()),
  ('cat_home-decor-and-accents-garden-decor','home-decor-and-accents-garden-decor','Garden Decor','cat_home-decor-and-accents',15,TRUE,FALSE,FALSE,FALSE,3,'home/decor-and-accents/garden-decor',NULL,NOW(),NOW()),
  ('cat_fragrance','fragrance','Fragrance',NULL,5,TRUE,FALSE,FALSE,FALSE,1,'fragrance',NULL,NOW(),NOW()),
  ('cat_fragrance-personal-fragrance','fragrance-personal-fragrance','Personal Fragrance','cat_fragrance',1,TRUE,FALSE,FALSE,FALSE,2,'fragrance/personal-fragrance',NULL,NOW(),NOW()),
  ('cat_fragrance-personal-fragrance-attars','fragrance-personal-fragrance-attars','Attars','cat_fragrance-personal-fragrance',1,TRUE,FALSE,FALSE,FALSE,3,'fragrance/personal-fragrance/attars',NULL,NOW(),NOW()),
  ('cat_fragrance-personal-fragrance-eau-de-parfum','fragrance-personal-fragrance-eau-de-parfum','Eau de Parfum','cat_fragrance-personal-fragrance',2,TRUE,FALSE,FALSE,FALSE,3,'fragrance/personal-fragrance/eau-de-parfum',NULL,NOW(),NOW()),
  ('cat_fragrance-personal-fragrance-eau-de-toilette','fragrance-personal-fragrance-eau-de-toilette','Eau de Toilette','cat_fragrance-personal-fragrance',3,TRUE,FALSE,FALSE,FALSE,3,'fragrance/personal-fragrance/eau-de-toilette',NULL,NOW(),NOW()),
  ('cat_fragrance-personal-fragrance-body-sprays','fragrance-personal-fragrance-body-sprays','Body Sprays','cat_fragrance-personal-fragrance',4,TRUE,FALSE,FALSE,FALSE,3,'fragrance/personal-fragrance/body-sprays',NULL,NOW(),NOW()),
  ('cat_fragrance-personal-fragrance-perfume-oils','fragrance-personal-fragrance-perfume-oils','Perfume Oils','cat_fragrance-personal-fragrance',5,TRUE,FALSE,FALSE,FALSE,3,'fragrance/personal-fragrance/perfume-oils',NULL,NOW(),NOW()),
  ('cat_fragrance-personal-fragrance-solid-perfumes','fragrance-personal-fragrance-solid-perfumes','Solid Perfumes','cat_fragrance-personal-fragrance',6,TRUE,FALSE,FALSE,FALSE,3,'fragrance/personal-fragrance/solid-perfumes',NULL,NOW(),NOW()),
  ('cat_fragrance-home-fragrance','fragrance-home-fragrance','Home Fragrance','cat_fragrance',2,TRUE,FALSE,FALSE,FALSE,2,'fragrance/home-fragrance',NULL,NOW(),NOW()),
  ('cat_fragrance-home-fragrance-incense-sticks','fragrance-home-fragrance-incense-sticks','Incense Sticks','cat_fragrance-home-fragrance',1,TRUE,FALSE,FALSE,FALSE,3,'fragrance/home-fragrance/incense-sticks',NULL,NOW(),NOW()),
  ('cat_fragrance-home-fragrance-dhoop','fragrance-home-fragrance-dhoop','Dhoop','cat_fragrance-home-fragrance',2,TRUE,FALSE,FALSE,FALSE,3,'fragrance/home-fragrance/dhoop',NULL,NOW(),NOW()),
  ('cat_fragrance-home-fragrance-cones','fragrance-home-fragrance-cones','Cones','cat_fragrance-home-fragrance',3,TRUE,FALSE,FALSE,FALSE,3,'fragrance/home-fragrance/cones',NULL,NOW(),NOW()),
  ('cat_fragrance-home-fragrance-diffusers','fragrance-home-fragrance-diffusers','Diffusers','cat_fragrance-home-fragrance',4,TRUE,FALSE,FALSE,FALSE,3,'fragrance/home-fragrance/diffusers',NULL,NOW(),NOW()),
  ('cat_fragrance-home-fragrance-reed-diffusers','fragrance-home-fragrance-reed-diffusers','Reed Diffusers','cat_fragrance-home-fragrance',5,TRUE,FALSE,FALSE,FALSE,3,'fragrance/home-fragrance/reed-diffusers',NULL,NOW(),NOW()),
  ('cat_fragrance-home-fragrance-room-sprays','fragrance-home-fragrance-room-sprays','Room Sprays','cat_fragrance-home-fragrance',6,TRUE,FALSE,FALSE,FALSE,3,'fragrance/home-fragrance/room-sprays',NULL,NOW(),NOW()),
  ('cat_fragrance-home-fragrance-scented-candles','fragrance-home-fragrance-scented-candles','Scented Candles','cat_fragrance-home-fragrance',7,TRUE,FALSE,FALSE,FALSE,3,'fragrance/home-fragrance/scented-candles',NULL,NOW(),NOW()),
  ('cat_fragrance-aromatherapy-and-oils','fragrance-aromatherapy-and-oils','Aromatherapy and Oils','cat_fragrance',3,TRUE,FALSE,FALSE,FALSE,2,'fragrance/aromatherapy-and-oils',NULL,NOW(),NOW()),
  ('cat_fragrance-aromatherapy-and-oils-essential-oils','fragrance-aromatherapy-and-oils-essential-oils','Essential Oils','cat_fragrance-aromatherapy-and-oils',1,TRUE,FALSE,FALSE,FALSE,3,'fragrance/aromatherapy-and-oils/essential-oils',NULL,NOW(),NOW()),
  ('cat_fragrance-aromatherapy-and-oils-massage-oils','fragrance-aromatherapy-and-oils-massage-oils','Massage Oils','cat_fragrance-aromatherapy-and-oils',2,TRUE,FALSE,FALSE,FALSE,3,'fragrance/aromatherapy-and-oils/massage-oils',NULL,NOW(),NOW()),
  ('cat_fragrance-aromatherapy-and-oils-wellness-blends','fragrance-aromatherapy-and-oils-wellness-blends','Wellness Blends','cat_fragrance-aromatherapy-and-oils',3,TRUE,FALSE,FALSE,FALSE,3,'fragrance/aromatherapy-and-oils/wellness-blends',NULL,NOW(),NOW()),
  ('cat_gifting','gifting','Gifting',NULL,6,TRUE,FALSE,FALSE,FALSE,1,'gifting',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion','gifting-by-occasion','By Occasion','cat_gifting',1,TRUE,FALSE,FALSE,FALSE,2,'gifting/by-occasion',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion-wedding','gifting-by-occasion-wedding','Wedding','cat_gifting-by-occasion',1,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-occasion/wedding',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion-anniversary','gifting-by-occasion-anniversary','Anniversary','cat_gifting-by-occasion',2,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-occasion/anniversary',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion-birthday','gifting-by-occasion-birthday','Birthday','cat_gifting-by-occasion',3,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-occasion/birthday',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion-diwali','gifting-by-occasion-diwali','Diwali','cat_gifting-by-occasion',4,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-occasion/diwali',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion-eid','gifting-by-occasion-eid','Eid','cat_gifting-by-occasion',5,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-occasion/eid',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion-holi','gifting-by-occasion-holi','Holi','cat_gifting-by-occasion',6,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-occasion/holi',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion-raksha-bandhan','gifting-by-occasion-raksha-bandhan','Raksha Bandhan','cat_gifting-by-occasion',7,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-occasion/raksha-bandhan',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion-housewarming','gifting-by-occasion-housewarming','Housewarming','cat_gifting-by-occasion',8,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-occasion/housewarming',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion-corporate','gifting-by-occasion-corporate','Corporate','cat_gifting-by-occasion',9,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-occasion/corporate',NULL,NOW(),NOW()),
  ('cat_gifting-by-occasion-thank-you','gifting-by-occasion-thank-you','Thank You','cat_gifting-by-occasion',10,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-occasion/thank-you',NULL,NOW(),NOW()),
  ('cat_gifting-by-recipient','gifting-by-recipient','By Recipient','cat_gifting',2,TRUE,FALSE,FALSE,FALSE,2,'gifting/by-recipient',NULL,NOW(),NOW()),
  ('cat_gifting-by-recipient-for-her','gifting-by-recipient-for-her','For Her','cat_gifting-by-recipient',1,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-recipient/for-her',NULL,NOW(),NOW()),
  ('cat_gifting-by-recipient-for-him','gifting-by-recipient-for-him','For Him','cat_gifting-by-recipient',2,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-recipient/for-him',NULL,NOW(),NOW()),
  ('cat_gifting-by-recipient-for-the-couple','gifting-by-recipient-for-the-couple','For the Couple','cat_gifting-by-recipient',3,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-recipient/for-the-couple',NULL,NOW(),NOW()),
  ('cat_gifting-by-recipient-for-the-home','gifting-by-recipient-for-the-home','For the Home','cat_gifting-by-recipient',4,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-recipient/for-the-home',NULL,NOW(),NOW()),
  ('cat_gifting-by-recipient-for-the-mom','gifting-by-recipient-for-the-mom','For the Mom','cat_gifting-by-recipient',5,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-recipient/for-the-mom',NULL,NOW(),NOW()),
  ('cat_gifting-by-recipient-for-the-boss','gifting-by-recipient-for-the-boss','For the Boss','cat_gifting-by-recipient',6,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-recipient/for-the-boss',NULL,NOW(),NOW()),
  ('cat_gifting-by-recipient-for-the-host','gifting-by-recipient-for-the-host','For the Host','cat_gifting-by-recipient',7,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-recipient/for-the-host',NULL,NOW(),NOW()),
  ('cat_gifting-by-price','gifting-by-price','By Price','cat_gifting',3,TRUE,FALSE,FALSE,FALSE,2,'gifting/by-price',NULL,NOW(),NOW()),
  ('cat_gifting-by-price-under-2500','gifting-by-price-under-2500','Under 2500','cat_gifting-by-price',1,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-price/under-2500',NULL,NOW(),NOW()),
  ('cat_gifting-by-price-2500-to-10000','gifting-by-price-2500-to-10000','2500 to 10000','cat_gifting-by-price',2,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-price/2500-to-10000',NULL,NOW(),NOW()),
  ('cat_gifting-by-price-10000-to-50000','gifting-by-price-10000-to-50000','10000 to 50000','cat_gifting-by-price',3,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-price/10000-to-50000',NULL,NOW(),NOW()),
  ('cat_gifting-by-price-above-50000','gifting-by-price-above-50000','Above 50000','cat_gifting-by-price',4,TRUE,FALSE,FALSE,FALSE,3,'gifting/by-price/above-50000',NULL,NOW(),NOW()),
  ('cat_gifting-stationery-and-paper','gifting-stationery-and-paper','Stationery and Paper','cat_gifting',4,TRUE,FALSE,FALSE,FALSE,2,'gifting/stationery-and-paper',NULL,NOW(),NOW()),
  ('cat_gifting-stationery-and-paper-notebooks','gifting-stationery-and-paper-notebooks','Notebooks','cat_gifting-stationery-and-paper',1,TRUE,FALSE,FALSE,FALSE,3,'gifting/stationery-and-paper/notebooks',NULL,NOW(),NOW()),
  ('cat_gifting-stationery-and-paper-journals','gifting-stationery-and-paper-journals','Journals','cat_gifting-stationery-and-paper',2,TRUE,FALSE,FALSE,FALSE,3,'gifting/stationery-and-paper/journals',NULL,NOW(),NOW()),
  ('cat_gifting-stationery-and-paper-pens','gifting-stationery-and-paper-pens','Pens','cat_gifting-stationery-and-paper',3,TRUE,FALSE,FALSE,FALSE,3,'gifting/stationery-and-paper/pens',NULL,NOW(),NOW()),
  ('cat_gifting-stationery-and-paper-inkwells','gifting-stationery-and-paper-inkwells','Inkwells','cat_gifting-stationery-and-paper',4,TRUE,FALSE,FALSE,FALSE,3,'gifting/stationery-and-paper/inkwells',NULL,NOW(),NOW()),
  ('cat_gifting-stationery-and-paper-stationery-sets','gifting-stationery-and-paper-stationery-sets','Stationery Sets','cat_gifting-stationery-and-paper',5,TRUE,FALSE,FALSE,FALSE,3,'gifting/stationery-and-paper/stationery-sets',NULL,NOW(),NOW()),
  ('cat_gifting-stationery-and-paper-cards','gifting-stationery-and-paper-cards','Cards','cat_gifting-stationery-and-paper',6,TRUE,FALSE,FALSE,FALSE,3,'gifting/stationery-and-paper/cards',NULL,NOW(),NOW()),
  ('cat_gifting-stationery-and-paper-wrapping-paper','gifting-stationery-and-paper-wrapping-paper','Wrapping Paper','cat_gifting-stationery-and-paper',7,TRUE,FALSE,FALSE,FALSE,3,'gifting/stationery-and-paper/wrapping-paper',NULL,NOW(),NOW()),
  ('cat_gifting-stationery-and-paper-bookmarks','gifting-stationery-and-paper-bookmarks','Bookmarks','cat_gifting-stationery-and-paper',8,TRUE,FALSE,FALSE,FALSE,3,'gifting/stationery-and-paper/bookmarks',NULL,NOW(),NOW())
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "parentId" = EXCLUDED."parentId",
  "order" = EXCLUDED."order",
  "level" = EXCLUDED."level",
  "path" = EXCLUDED."path",
  "gender" = EXCLUDED."gender",
  "updatedAt" = NOW();

-- =========================================================
-- 4) RE-ADD FK CONSTRAINT now that all rows are present
-- =========================================================
ALTER TABLE "Category" ADD CONSTRAINT "Category_parentId_fkey"
  FOREIGN KEY ("parentId") REFERENCES "Category"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- =========================================================
-- 5) REDIRECTS for renamed / merged categories
-- =========================================================
INSERT INTO "CategoryRedirect" ("id","fromSlug","toSlug","permanent","createdAt","updatedAt") VALUES
  ('redir_jewellery','jewellery','accessories/jewellery',TRUE,NOW(),NOW()),
  ('redir_women-jewellery','women-jewellery','accessories/jewellery',TRUE,NOW(),NOW()),
  ('redir_men-accessories','men-accessories','accessories',TRUE,NOW(),NOW()),
  ('redir_women-accessories','women-accessories','accessories',TRUE,NOW(),NOW()),
  ('redir_home-furniture','home-furniture','home/furniture',TRUE,NOW(),NOW()),
  ('redir_home-lighting','home-lighting','home/lighting-decorative',TRUE,NOW(),NOW()),
  ('redir_home-kitchen','home-kitchen','home/kitchen',TRUE,NOW(),NOW()),
  ('redir_home-bar','home-bar','home/bar',TRUE,NOW(),NOW()),
  ('redir_personal-care','personal-care','accessories/personal-care',TRUE,NOW(),NOW()),
  ('redir_grooming','grooming','accessories/personal-care',TRUE,NOW(),NOW()),
  ('redir_perfume','perfume','fragrance/personal-fragrance',TRUE,NOW(),NOW()),
  ('redir_attar','attar','fragrance/personal-fragrance',TRUE,NOW(),NOW()),
  ('redir_incense','incense','fragrance/home-fragrance',TRUE,NOW(),NOW()),
  ('redir_candle','candle','home/decor-and-accents',TRUE,NOW(),NOW()),
  ('redir_notebook','notebook','gifting/stationery-and-paper',TRUE,NOW(),NOW()),
  ('redir_stationery','stationery','gifting/stationery-and-paper',TRUE,NOW(),NOW())
ON CONFLICT ("fromSlug") DO UPDATE SET
  "toSlug" = EXCLUDED."toSlug",
  "updatedAt" = NOW();

-- =========================================================
-- 6) VERIFICATION: count by level
-- =========================================================
SELECT level, COUNT(*) as count FROM "Category" GROUP BY level ORDER BY level;